spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
