server:
  port: 8083

spring:
  application:
    name: DEPARTMENT-SERVICE

  datasource:
    url: jdbc:postgresql://postgres:5432/departmentdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
