server:
  port: 8082

spring:
  application:
    name: EMPLOYEE-SERVICE

  datasource:
    url: jdbc:postgresql://postgres:5432/employeedb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

# -------------------------
# RESILIENCE4J CONFIGURATION
# -------------------------
resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
